Remove Travis dev env and change draft/staging to those branches
OpenLiberty/openliberty.io pull request #1844
Opened 2020-09-02 16:38 UTC by steven1046

#### What was fixed?  (Issue # or description of fix)
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] Dymanic Accessability Plugin (DAP)
- [ ] Lighthouse (in Chrome dev tools)

2020-09-03 19:20 UTC, steven1046 commented
These changes will also need to go into `staging` once they go into `draft`.

2020-09-04 17:06 UTC, mbroz2 requested changes

2020-09-04 17:06 UTC, mbroz2 commented on .travis.yml
> +    script: ./.travis/cf-push-2.sh
Shouldn't we get rid of `cf-push-2.sh` and just make `.travis/cf-push.sh` take a param for the Bluemix org?
`script: ./.travis/cf-push.sh BLUEMIX_ORGANIZATION` (default to BLUEMIX_ORGANIZATION if nothing passed in)
`script: ./.travis/cf-push.sh BLUEMIX_ORGANIZATION_2`

2020-09-08 14:02 UTC, mbroz2 approved these changes

2020-09-08 14:17 UTC, merged