Starter none msg issue
OpenLiberty/openliberty.io pull request #2724
Opened 2022-06-27 10:00 UTC by Sreejith-Websphere

#### What was fixed?  (Issue # or description of fix)
#### Were the changes tested on
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)
- [ ] Internet Explorer (Desktop)
- [ ] iOS (Mobile)
- [ ] Android (Mobile)
#### Running validation tools
- [ ] https://validator.w3.org/checklink
- [ ] https://validator.w3.org
- [ ] IBM Equal Access Accessibility Checker (https://www.ibm.com/able/toolkit/verify/automated)
- [ ] Lighthouse (in Chrome dev tools)

2022-06-27 16:15 UTC, kinueng commented
Let's make sure we write Cypress test cases to ensure the message is shown when it makes sense

2022-06-28 09:42 UTC, Sreejith-Websphere commented
@kinueng @aknguyen7 cypress test case added

2022-07-07 17:11 UTC, aknguyen7 commented on src/test/cypressjs/cypress/integration/testOLStarterJakartaMPNone.js
> +        cy.get('#starter_warnings p').should('not.exist') //message should not be shown
I assume this `#starter_warnings p` works? I'd normally see the syntax for cypress like `#starter_warings>p` instead

2022-07-07 19:20 UTC, aknguyen7 reviewed
the rest LGTM

2022-07-11 07:56 UTC, Sreejith-Websphere commented on src/test/cypressjs/cypress/integration/testOLStarterJakartaMPNone.js
> +        cy.get('#starter_warnings p').should('not.exist') //message should not be shown
Hi @aknguyen7 this cypress syntax works #starter_warnings p, below is the example I just changed the test case to fail, can see that syntax works

<img width="1792" alt="Screenshot 2022-07-11 at 1 23 43 PM" src="https://user-images.githubusercontent.com/87368885/178215988-f4eab460-c390-42fa-b33f-a1ff59c119ee.png">

2022-07-11 20:24 UTC, kinueng requested changes

2022-07-11 20:24 UTC, kinueng commented on src/main/content/_assets/js/builds.js
> +                if ((EEVersionValue == "None")&&(prev_selected_mp_version == "None")) {
```suggestion
                if((EEVersionValue === "None") && (prev_selected_mp_version === "None")) {
```

I would suggest always prefer `===` over `==` unless type conversion is needed. In this case, I believe the code is always dealing with String type and no type conversion is expected.

2022-07-11 20:24 UTC, kinueng commented on src/main/content/_assets/js/builds.js
> +                    if(mpVersionValue !== "None"){
```suggestion
                    if(mpVersionValue !== "None") {
```

For code consistency

2022-07-11 20:24 UTC, kinueng commented on src/main/content/_assets/js/builds.js
> +                    if((mpVersionValue == "None")&&(prev_selected_ee_version == "None")) {
```suggestion
                    if((mpVersionValue === "None") && (prev_selected_ee_version === "None")) {
```

2022-07-12 07:51 UTC, Sreejith-Websphere commented on src/main/content/_assets/js/builds.js
> +                if ((EEVersionValue == "None")&&(prev_selected_mp_version == "None")) {
Done

2022-07-12 15:24 UTC, kinueng approved these changes
LGTM

2022-07-12 15:24 UTC, merged