Add Open Liberty APIs/SPIs to the SEO on docs
OpenLiberty/openliberty.io pull request #3323
Opened 2023-08-14 17:37 UTC by steven1046

## What was changed and why?
Added Open Liberty APIs/SPIs to the SEO for docs.
Fixes #3293

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

2023-08-14 17:38 UTC, steven1046 commented
@chirp1, can you please review the wording change for SEO to include Open Liberty APIs/SPIs? Since Open Liberty are the only SPIs on the website, i added API to each of the other kind of javadocs in the sentence to show only Open Liberty have APIs and SPIs. Maybe we could make it a new sentence if it's too long.

2023-08-15 12:53 UTC, chirp1 commented
@dmuelle @ramkumar-k-9286 Hi! Since you are working on the API/SPI landing pages, would you review for Steven? Thanks!

2023-08-15 12:59 UTC, dmuelle commented
Hi Steven- where does this text show up?

2023-08-15 13:04 UTC, dmuelle requested changes
ID review- minor edits for clarity and sentence length

2023-08-15 13:04 UTC, dmuelle commented on src/main/content/antora_ui/src/partials/head-meta.hbs
> +<meta name="description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deploy worklo
```suggestion
<meta name="description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deploy workloads to clouds by using open cloud-native Java. This content covers Open Liberty basics, development, security, deployment, and operations topics. It also includes  Javadoc for Jakarta EE APIs, MicroProfile APIs, Java EE APIs, and Open Liberty APIs and SPIs.">
```

2023-08-15 13:04 UTC, dmuelle commented on src/main/content/antora_ui/src/partials/head-meta.hbs
> +<meta name="twitter:description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deplo
```suggestion
<meta name="description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deploy workloads to clouds by using open cloud-native Java. This content covers Open Liberty basics, development, security, deployment, and operations topics. It also includes  Javadoc for Jakarta EE APIs, MicroProfile APIs, Java EE APIs, and Open Liberty APIs and SPIs.">
```

2023-08-15 13:04 UTC, dmuelle commented on src/main/content/antora_ui/src/partials/head-meta.hbs
> +<meta property="og:description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deploy
```suggestion
<meta property="og:description" content="Open Liberty documentation and reference materials for developers to build applications and for administrators and operation teams to manage DevOps and deploy workloads to clouds by using open cloud-native Java. This content covers Open Liberty basics, development, security, deployment, and operations topics. It also includes  Javadoc for Jakarta EE APIs, MicroProfile APIs, Java EE APIs, and Open Liberty APIs and SPIs.">
```

2023-08-15 13:43 UTC, steven1046 commented
> Hi Steven- where does this text show up?

When people see links to our docs on Google and Twitter.

2023-08-15 14:03 UTC, dmuelle approved these changes
LGTM, thanks

2023-08-15 14:07 UTC, merged