Accessibility errors of guides section id addressed
OpenLiberty/openliberty.io pull request #3486
Opened 2023-11-14 08:57 UTC by navaneethsnair1

## What was changed and why?
Various changes were made to address accessibility errors inside guides section
## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2023-11-14 14:44 UTC, steven1046 approved these changes, later dismissed

2023-11-17 16:58 UTC, natalie-bernhard requested changes

2023-11-17 16:58 UTC, natalie-bernhard commented on src/main/content/_assets/js/guide-common.js
> +preTags.forEach(preTag => {
Same as my comment on the other PR, please change this to a standard for loop

2023-11-17 16:58 UTC, natalie-bernhard commented on src/main/content/_assets/js/guide-common.js
> +preTags.forEach(preTag => {
Also, is it possible for you to rewrite this using the jQuery library (like the attr function you used later in the file)?  If you need any help or guidance, please reach out!

2023-11-20 14:19 UTC, natalie-bernhard approved these changes

2023-11-20 17:20 UTC, merged