changed to telemetry
OpenLiberty/openliberty.io pull request #3497
Opened 2023-11-20 17:18 UTC by navaneethsnair1

## What was changed and why?
Link to issue is [here](https://github.com/OpenLiberty/openliberty.io/issues/3491).
It was updated from 'Open Telemetry' to 'Telemetry'.

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2023-11-27 14:05 UTC, steven1046 submitted a review, later dismissed

2023-11-27 14:07 UTC, natalie-bernhard requested changes
Please rebase this branch onto the prod branch, then open a new PR into draft in order to correct the Github history. If you are unfamiliar with rebasing, start with this article: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase. Let me know if you have any questions.

2023-11-29 14:47 UTC, natalie-bernhard commented
@steven1046 This is ready for review.

2023-11-29 14:52 UTC, steven1046 approved these changes

2023-11-29 20:04 UTC, natalie-bernhard approved these changes

2023-11-30 04:25 UTC, merged