Combined multiple starter warnings into a single warning
OpenLiberty/openliberty.io pull request #3503
Opened 2023-11-27 07:43 UTC by SteveSamJacob19

## What was changed and why?

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2023-11-27 14:14 UTC, natalie-bernhard requested changes
This branch needs to be rebased onto the current prod branch.  If you don't know about rebasing a branch, start with this article: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase.  Let me know if you have any questions.

2023-11-27 15:03 UTC, steven1046 requested changes

2023-11-27 15:03 UTC, steven1046 commented on src/main/content/_assets/js/builds.js
> +    $('#starter_warnings li:first-child').css("padding-top","20px");
Can you move these styles to a css file since they don't seem to change based on logic

2023-11-27 15:04 UTC, steven1046 commented
@SteveSamJacob19 can you please upload a screenshot of what the design looks like so @natalie-bernhard and others that view the history can see?

2023-11-27 15:41 UTC, SteveSamJacob19 commented
<img width="1728" alt="Screenshot 2023-11-27 at 9 08 24 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/788a7315-00ec-4b44-8165-5d20bc9ed403">

2023-11-29 14:59 UTC, natalie-bernhard commented
Hi, can you make the spacing around the X more equal? Also, could you add a border-radius to the p element in the warning with a value of 7px so it matches the rounded appearance of the text boxes above it?

2023-12-04 06:49 UTC, SteveSamJacob19 commented
@natalie-bernhard I have made the requested changes

2023-12-04 14:53 UTC, natalie-bernhard commented
> @natalie-bernhard I have made the requested changes

Can you add a new screenshot of the changes?

2023-12-04 14:56 UTC, SteveSamJacob19 commented
<img width="1728" alt="Screenshot 2023-12-04 at 12 19 14 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/cd1f4b7b-2af3-4804-b774-8c9d5421a8bb">
Is this fine?

2023-12-04 15:32 UTC, natalie-bernhard commented
<img width="1083" alt="Screenshot 2023-12-04 at 9 31 27 AM" src="https://github.com/OpenLiberty/openliberty.io/assets/84740311/80ce09ac-6d11-4cf3-81e5-a3502bb86b1e">
The corners of the box should be curved like this from adding the border radius CSS rule mentioned in my earlier comment.

2023-12-06 06:24 UTC, SteveSamJacob19 commented
<img width="1728" alt="Screenshot 2023-12-06 at 11 51 40 AM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/69a484d5-04a6-431a-a54a-727a956b83ca">
How is this?

2023-12-06 16:15 UTC, natalie-bernhard commented
Hi sorry to be picky, but can you decrease the spacing between the two lines of text? They look a little far apart at the moment.

2023-12-07 08:13 UTC, SteveSamJacob19 commented
@natalie-bernhard is this fine
<img width="1728" alt="Screenshot 2023-12-07 at 1 42 40 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/87b5f492-06fc-45ab-acaf-3ea71e7e1950">

2023-12-11 16:26 UTC, steven1046 approved these changes

2023-12-11 16:52 UTC, natalie-bernhard commented
Yes this looks great, thank you! Merging this now as I had to do some git clean-up for the branch which led to the reviews getting messed up.

2023-12-11 16:52 UTC, merged