Lowercasing blog and guide tags
OpenLiberty/openliberty.io pull request #3540
Opened 2024-01-03 06:20 UTC by SteveSamJacob19

## What was changed and why?

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2024-01-03 14:28 UTC, steven1046 submitted a review, later dismissed

2024-01-03 14:37 UTC, natalie-bernhard requested changes
Branch needs to be rebased

2024-01-03 15:27 UTC, steven1046 approved these changes

2024-01-08 06:33 UTC, SteveSamJacob19 reviewed
Has been merged with prod

2024-01-08 14:06 UTC, natalie-bernhard approved these changes

2024-01-08 19:48 UTC, merged