Version links of Releases table in get started page
OpenLiberty/openliberty.io pull request #3556
Opened 2024-01-10 06:00 UTC by navaneethsnair1

## What was changed and why?
Links to each versions in _Releases table_ is provided. Link to the issue [here](https://github.com/OpenLiberty/openliberty.io/issues/3520)

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2024-01-10 15:03 UTC, steven1046 commented
I think we need to rebase the branch on draft

2024-01-18 17:17 UTC, natalie-bernhard requested changes
Also please merge prod into this branch, thank you

2024-01-18 17:17 UTC, natalie-bernhard commented on src/main/content/_assets/js/builds.js
> +                            '">' + '<a href="#' +
You should be able to remove this <a> element.

2024-01-19 15:41 UTC, natalie-bernhard approved these changes

2024-01-19 15:41 UTC, merged