Fixed overlapping of TOC accordion
OpenLiberty/openliberty.io pull request #3566
Opened 2024-01-18 06:25 UTC by SteveSamJacob19

Also changed the z-index issue of the toc accordion by changing its z-index to 10000 as the copy_confirm button has z-index of 9997

2024-01-19 15:47 UTC, natalie-bernhard requested changes
Once you have addressed the other comments, please rebase this branch onto draft

2024-01-19 15:47 UTC, natalie-bernhard commented on src/main/content/_assets/js/openliberty.js
> +        var mobile = document.getElementById('mobile_toc_accordion_container');
Can you make line 86 also Jquery please?

2024-01-19 15:47 UTC, natalie-bernhard commented on src/main/content/_assets/js/openliberty.js
> +            console.log("class found");
please remove this console.log

2024-01-19 15:47 UTC, natalie-bernhard commented on src/main/content/_assets/js/openliberty.js
> +        var mobile = document.getElementById('mobile_toc_accordion_container');
Please change line 129 to use Jquery

2024-01-19 17:04 UTC, natalie-bernhard requested changes

2024-01-19 17:04 UTC, natalie-bernhard commented on src/main/content/_assets/js/openliberty.js
> +            console.log("class found");
Please remove this console.log

2024-01-22 14:31 UTC, steven1046 approved these changes

2024-01-22 14:33 UTC, natalie-bernhard approved these changes

2024-01-22 14:33 UTC, merged