Fixed blog author githu id being clickable
OpenLiberty/openliberty.io pull request #3571
Opened 2024-01-22 07:13 UTC by SteveSamJacob19

## What was changed and why?

## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2024-01-22 08:38 UTC, SteveSamJacob19 commented
Have to rebase it, will rebase once rebasing for other PR is done

2024-01-23 07:05 UTC, SteveSamJacob19 commented
@natalie-bernhard I  have rebased it to draft

2024-01-23 14:21 UTC, natalie-bernhard requested changes

2024-01-23 14:21 UTC, natalie-bernhard commented on src/main/content/_layouts/post.html
> +                        <a class="author_name" target="_blank" rel="noopener">{{ page.author }}</a>
Please change this to be a span element instead: 
`<span class="blog_post_author_name">{{ page.author }}</span>`

2024-01-23 14:21 UTC, natalie-bernhard commented on src/main/content/blog.html
> +            <a class="blog_post_author_name" rel="noopener" target="_blank">
Please change this to a span element.

2024-01-23 14:21 UTC, natalie-bernhard commented on src/main/content/blog.html
> +            <a class="blog_post_author_name" rel="noopener" target="_blank">
Please change this to a span element.

2024-01-23 14:21 UTC, natalie-bernhard commented on src/main/content/index.html
> +                                <a class="blog_post_author_name" rel="noopener" target="_blank">
Please change this to a span element.

2024-01-23 14:21 UTC, natalie-bernhard commented on src/main/content/index.html
> +                                <a class="blog_post_author_name" rel="noopener" target="_blank">
Please change this to a span element.

2024-01-23 14:40 UTC, SteveSamJacob19 commented
@natalie-bernhard made the changes as requested

2024-01-29 16:48 UTC, natalie-bernhard approved these changes

2024-01-29 16:48 UTC, merged