Address issues associated with guides code column in singlepane
OpenLiberty/openliberty.io pull request #3851
Opened 2024-09-18 11:49 UTC by navaneethsnair1

## What was changed and why?
New design approach solving existing errors of guides' code column when in singlepane. Link to issue []([here](https://github.com/OpenLiberty/openliberty.io/issues/1360))
## Tested using browser:
- [ ] Firefox (Desktop)
- [ ] Safari (Desktop)
- [ ] Chrome (Desktop)

## Did you test accessibility:
- [ ] IBM Equal Access Accessibilty Checker
- [ ] Jaws (only relevant for new UX flows)

2024-09-20 05:44 UTC, SteveSamJacob19 requested changes
please remove ur comments

2024-09-20 05:44 UTC, SteveSamJacob19 commented on src/main/content/_assets/css/guide-common.scss
> +@media (max-width: 1169.98px){//me added
please remove such comments

2024-09-20 09:32 UTC, navaneethsnair1 commented on src/main/content/_assets/css/guide-common.scss
> +@media (max-width: 1169.98px){//me added
That was by mistake, pardon me.

2024-09-24 13:51 UTC, SteveSamJacob19 approved these changes

2024-09-24 13:51 UTC, merged